INSERT INTO `produtos` (`id`, `name`, `price`, `category`, `launch_date`, `image_url`) VALUES 
(1, 'Carne - Carne de Vaca', 26, 'Alimentos', '2024-09-17', 'https://example.com/images/beef.jpg'),
(2, 'Óleo - Azeite de Oliva', 12, 'Alimentos', '2024-10-23', 'https://example.com/images/olive-oil.jpg'),
(3, 'Frango - Coxa com Osso', 15, 'Alimentos', '2024-07-14', 'https://example.com/images/chicken-thigh.jpg'),
(4, 'Suco - Limão', 8, 'Bebidas', '2024-09-06', 'https://example.com/images/lime-juice.jpg'),
(5, 'Vinho - Branco, Cruz Francesa', 61, 'Bebidas', '2024-01-19', 'https://example.com/images/white-wine.jpg'),
(6, 'Açúcar - Cubos', 5, 'Alimentos', '2024-05-09', 'https://example.com/images/sugar-cubes.jpg'),
(7, 'Suco - Maçã, 341 Ml', 7, 'Bebidas', '2023-12-25', 'https://example.com/images/apple-juice.jpg'),
(8, 'Purê de Batata Instantâneo', 6, 'Alimentos', '2023-12-16', 'https://example.com/images/mashed-potatoes.jpg'),
(9, 'Vodka - Limão, Absolut', 36, 'Bebidas Alcoólicas', '2024-07-14', 'https://example.com/images/lemon-vodka.jpg'),
(10, 'Corações de Taboa', 15, 'Alimentos', '2024-03-16', 'https://example.com/images/cattail-hearts.jpg'),
(11, 'Sanduíches de Vegetais Grelhados', 10, 'Alimentos', '2024-06-07', 'https://example.com/images/grilled-veg-sandwich.jpg'),
(12, 'Abacate', 4, 'Alimentos', '2024-04-29', 'https://example.com/images/avocado.jpg'),
(13, 'Xarope - Monin, Creme Irlandês', 10, 'Bebidas', '2024-03-30', 'https://example.com/images/irish-cream-syrup.jpg'),
(14, 'Garam Masala', 20, 'Alimentos', '2023-11-22', 'https://example.com/images/garam-marsala.jpg'),
(15, 'Abóbora', 3, 'Alimentos', '2024-05-29', 'https://example.com/images/pepper-squash.jpg'),
(16, 'Pasta de Tomate', 6, 'Alimentos', '2024-03-01', 'https://example.com/images/tomato-paste.jpg'),
(17, 'Queijo - Cream Cheese para Cozimento', 10, 'Laticínios', '2024-08-30', 'https://example.com/images/cream-cheese.jpg'),
(18, 'Óleo - Trufas Brancas', 50, 'Alimentos Gourmet', '2024-06-10', 'https://example.com/images/white-truffle-oil.jpg'),
(19, 'Vinho - Sogrape Mateus Rosé', 89, 'Bebidas Alcoólicas', '2024-09-30', 'https://example.com/images/mateus-rose.jpg'),
(20, 'Alecrim Seco', 5, 'Especiarias', '2024-09-04', 'https://example.com/images/dried-rosemary.jpg');